### ISSUE TITLE
glsdr: java.lang.IllegalstateException when device has no microphone

### ISSUE THREAD

**Issue by f4exb** [alexlee188/ghpsdr3-alex#38]
Hello, 

this concerns the Android client glsdr on the opengl branch. I am actually using the 1.48 version (latest) from the Play Store but this should refer to the same code.

I tried to run glsdr on a platform with no microphone nor any audio input device. This is the Nvidia Shield TV on a standard Android 5.1 thus I don't have access to the microphone on the gamepad since the gamepad is not recognized on a standard Amdroid (only the Nvidia version). Actually glsdr is working on the Nvidia Android so this problem looked weird to me at first.

The full stack trace is:

```
FATAL EXCEPTION: main
Process: org.v1al, PID: 15433
java.lang.IllegalStateException: stop() called on an uninitialized AudioRecord.
at android.media.AudioRecord.stop(AudioRecord.java:652)
at org.v1al.Connection.close(Connection.java:119)
at org.v1al.AHPSDRActivity$20.onClick(AHPSDRActivity.java:1325)
at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:162)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5254)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

Searching the net with this exception text quickly pointed me to an audio recording problem and I remembered that glsdr required the use of a microphone at install time. 

So I plugged in an USB camera with microphone into one of the USB ports and glsdr started to work like by magic.

I think however that devices without microphone should be supported as glsdr is mainly used for Rx rather than for Tx.

Best regards.

**Comment by alexlee188** [comment]
Thanks.  I will look into this.

Alex

**Comment by alexlee188** [comment]
Please test the attached glSDR app and see whether it works with and
without MIC.

**Comment by f4exb** [comment]
Hello Alex,

thanks for your update! However I don't see any .apk in attachment. Did you forget to attach it? Or where can I find it?

Best regards,
Edouard.

On Sat, 13 Feb 2016 22:47:34 -0800
alexlee188 <notifications@github.com> wrote:

> Please test the attached glSDR app and see whether it works with and
> without MIC.
> 
> On Thu, Feb 11, 2016 at 8:38 AM, f4exb <notifications@github.com> wrote:
> 
> > Hello,
> >
> > this concerns the Android client glsdr on the opengl branch. I am actually
> > using the 1.48 version (latest) from the Play Store but this should refer
> > to the same code.
> >
> > I tried run glsdr on a platform with no microphone nor any audio input
> > device. This is the Nvidia Shield TV on a standard Android 5.1 thus I don't
> > have access to the microphone on the gamepad since the gamepad is not
> > recognized on a standard Amdroid (only the Nvidia version). Actually glsdr
> > is working on the Nvidia Android so this problem looked weird to me at
> > first.
> >
> > The full stack trace is:
> >
> > FATAL EXCEPTION: main
> > Process: org.v1al, PID: 15433
> > java.lang.IllegalStateException: stop() called on an uninitialized AudioRecord.
> > at android.media.AudioRecord.stop(AudioRecord.java:652)
> > at org.v1al.Connection.close(Connection.java:119)
> > at org.v1al.AHPSDRActivity$20.onClick(AHPSDRActivity.java:1325)
> > at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:162)
> > at android.os.Handler.dispatchMessage(Handler.java:102)
> > at android.os.Looper.loop(Looper.java:135)
> > at android.app.ActivityThread.main(ActivityThread.java:5254)
> > at java.lang.reflect.Method.invoke(Native Method)
> > at java.lang.reflect.Method.invoke(Method.java:372)
> > at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
> > at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
> >
> > Searching the net with this exception text quickly pointed me to an audio
> > recording problem and I remembered that glsdr required the use of a
> > microphone at install time.
> >
> > So I plugged in an USB camera with microphone one one of the USB ports and
> > glsdr started to work like by magic.
> >
> > I think however that devices without microphone should be supported as
> > glsdr is mainly used for Rx rather than for Tx.
> >
> > Best regards.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/alexlee188/ghpsdr3-alex/issues/38>.
> >
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/alexlee188/ghpsdr3-alex/issues/38#issuecomment-183837404

-- 
F4EXB <f4exb@free.fr>

**Comment by alexlee188** [comment]
What is your direct email address?  Github must have removed the attached
file.

**Comment by f4exb** [comment]
Hello Alex,

please use f4exb@free.fr

Thnks!
Edouard.

On Wed, 24 Feb 2016 15:54:04 -0800
alexlee188 <notifications@github.com> wrote:

> What is your direct email address?  Github must have removed the attached
> file.
> 
> On Thu, 25 Feb, 2016 4:39 am f4exb <notifications@github.com> wrote:
> 
> > Hello Alex,
> >
> > thanks for your update! However I don't see any .apk in attachment. Did
> > you forget to attach it? Or where can I find it?
> >
> > Best regards,
> > Edouard.
> >
> > On Sat, 13 Feb 2016 22:47:34 -0800
> > alexlee188 <notifications@github.com> wrote:
> >
> > > Please test the attached glSDR app and see whether it works with and
> > > without MIC.
> > >
> > > On Thu, Feb 11, 2016 at 8:38 AM, f4exb <notifications@github.com> wrote:
> > >
> > > > Hello,
> > > >
> > > > this concerns the Android client glsdr on the opengl branch. I am
> > actually
> > > > using the 1.48 version (latest) from the Play Store but this should
> > refer
> > > > to the same code.
> > > >
> > > > I tried run glsdr on a platform with no microphone nor any audio input
> > > > device. This is the Nvidia Shield TV on a standard Android 5.1 thus I
> > don't
> > > > have access to the microphone on the gamepad since the gamepad is not
> > > > recognized on a standard Amdroid (only the Nvidia version). Actually
> > glsdr
> > > > is working on the Nvidia Android so this problem looked weird to me at
> > > > first.
> > > >
> > > > The full stack trace is:
> > > >
> > > > FATAL EXCEPTION: main
> > > > Process: org.v1al, PID: 15433
> > > > java.lang.IllegalStateException: stop() called on an uninitialized
> > AudioRecord.
> > > > at android.media.AudioRecord.stop(AudioRecord.java:652)
> > > > at org.v1al.Connection.close(Connection.java:119)
> > > > at org.v1al.AHPSDRActivity$20.onClick(AHPSDRActivity.java:1325)
> > > > at
> > com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:162)
> > > > at android.os.Handler.dispatchMessage(Handler.java:102)
> > > > at android.os.Looper.loop(Looper.java:135)
> > > > at android.app.ActivityThread.main(ActivityThread.java:5254)
> > > > at java.lang.reflect.Method.invoke(Native Method)
> > > > at java.lang.reflect.Method.invoke(Method.java:372)
> > > > at
> > com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
> > > > at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
> > > >
> > > > Searching the net with this exception text quickly pointed me to an
> > audio
> > > > recording problem and I remembered that glsdr required the use of a
> > > > microphone at install time.
> > > >
> > > > So I plugged in an USB camera with microphone one one of the USB ports
> > and
> > > > glsdr started to work like by magic.
> > > >
> > > > I think however that devices without microphone should be supported as
> > > > glsdr is mainly used for Rx rather than for Tx.
> > > >
> > > > Best regards.
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/alexlee188/ghpsdr3-alex/issues/38>.
> > > >
> > >
> > >
> > > ---
> > > Reply to this email directly or view it on GitHub:
> > >
> > https://github.com/alexlee188/ghpsdr3-alex/issues/38#issuecomment-183837404
> >
> > --
> > F4EXB <f4exb@free.fr>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/alexlee188/ghpsdr3-alex/issues/38#issuecomment-188446232>
> > .
> >
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/alexlee188/ghpsdr3-alex/issues/38#issuecomment-188524520

-- 
F4EXB <f4exb@free.fr>
