### ISSUE TITLE
Typo in HiQSDR IQ data format?

### ISSUE THREAD

**Issue by pavlus** [alexlee188/ghpsdr3-alex#40]
https://github.com/alexlee188/ghpsdr3-alex/blob/master/trunk/src/hiqsdr/hiqsdr.cpp#L902-L903

> #define i_sample(x) ((unsigned long)(x.i1 | (x.i2 << 8) | (x.i2 << 16)))
> #define q_sample(x) ((unsigned long)(x.q1 | (x.q2 << 8) | (x.q2 << 16)))

Shouldn't it use i3 and q3?

**Comment by alexlee188** [comment]
Roger (author of HiQSDR code) says:

Yes it should, but the macro is never used.

**Comment by recri** [comment]
I think you have your Roger's confused.  I just looked at the source and
noted that the macros were never referenced.

-- rec -- ad5dz --
