### ISSUE TITLE
missing/unavailable libsdrutil

### ISSUE THREAD

**Issue by csylvain** [alexlee188/ghpsdr3-alex#55]
unable to build ghpsdr3-alex. stalled at making dspserver.
```
Making all in trunk/src/dspserver
make[2]: Entering directory '/home/csylvain/Software/ghpsdr3-alex/trunk/src/dspserver'
/bin/bash ../../../libtool  --tag=CC   --mode=link gcc -O3 -Wall -I../../../trunk/src/DttSP -Wno-unused-function -L../../../trunk/src/DttSP -L.   -ffast-math -fopenmp  -march=native  -g -O2 -I/usr/include/libusb-1.0/ -I/usr/local/include/  -L/lib64 -L/usr/lib64 -o dspserver dspserver-main.o dspserver-ozy.o dspserver-soundcard.o dspserver-client.o dspserver-audiostream.o dspserver-register.o dspserver-rtp.o dspserver-G711A.o -lDttSP -lsdrutil -lrt -lssl -lcrypto  -lgomp -lortp -lsamplerate -levent_openssl -levent_pthreads -levent -lusb-1.0 -lconfig -ljack -lusb -lpulse -lpulse-simple -lcodec2 -lfftw3f -lportaudio -lpthread -lm 
libtool: link: gcc -O3 -Wall -I../../../trunk/src/DttSP -Wno-unused-function -ffast-math -fopenmp -march=native -g -O2 -I/usr/include/libusb-1.0/ -I/usr/local/include/ -o dspserver dspserver-main.o dspserver-ozy.o dspserver-soundcard.o dspserver-client.o dspserver-audiostream.o dspserver-register.o dspserver-rtp.o dspserver-G711A.o  -L../../../trunk/src/DttSP -L. -L/lib64 -L/usr/lib64 -lDttSP -lsdrutil -lrt -lssl -lcrypto -lgomp -lortp -lsamplerate -levent_openssl -levent_pthreads -levent -lusb-1.0 -lconfig -ljack -lusb -lpulse -lpulse-simple -lcodec2 -lfftw3f -lportaudio -lpthread -lm -fopenmp
/usr/bin/ld: cannot find -lsdrutil
collect2: error: ld returned 1 exit status
```
i'm guessing libsdrutil is part of (or the result of) building DttSP? in any case `http://dttsp.sourceforge.net/cvs.html` does not provide code because the host 'cvs.sourceforge.net' is not known.

i do have libwdsp available, though. can ghpsdr3 be reworked to use that instead (if it is equivalent)?

libsdrutil seems a mysterious library, on account i searched all over the place and find few hits other than makefiles referencing it!

**Comment by recri** [comment]
My build fails compiling the ortp code in dspserver, doesn't get to the
link phase.

libsdrutil should be built in trunk/src/dspserver from util.h and util.c,
did you install libtools?

-- rec --

**Comment by csylvain** [comment]
there's no libsdrutil.a in my dspserver directory. yes, i have libtool.
pretty sure 'configure' checked for that.
shouldn't the linking line have "libsdrutil.a" and not "-lsdrutil" .. the
latter assumes a system-wide dynamic directory?

$ libtool --version
libtool (GNU libtool) 2.4.6
Written by Gordon Matzigkeit, 1996

Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by csylvain** [comment]
correction to previous:
system-wide _dynamically linked_ _library_ ?

**Comment by recri** [comment]
cd trunk/src/dspserver && make libsdrutil.a && make

the -L. in the link command line includes the current directory in the library search path, I don't even know why it should be a library at all.

**Comment by csylvain** [comment]
thanks! that broke the logjam.  why the makefile is putting in "-lsdrutil"
as if there would be a libsdrutil.so when instead it should put in
"libsdrutil.a" (and also probably trigger it getting built because it is a
dependency), i don't know.

progressed to EqualizerDialog.cpp and blew up due to no <QAudioFormat> to
#include .. think that's referenced in UI.h .. fixed by installing
qtmultimedia5-dev package. configure should probably check for that, yes?

got all the down to the final link of QtRadio and it blows up not finding
"-lQtMultimedia" .. that definitely needs to be "-lQt5Multimedia" .. i'll
manually edit the makefile in trunk/src/QtRadio.

Makefile:QT_ADDITIONAL_LDFLAG = -lQtMultimedia
  changed to
Makefile:QT_ADDITIONAL_LDFLAG = -lQt5Multimedia

\o/  success!

**Comment by thermochromic** [comment]
Could not build on Ubuntu Focal
`mv -f .deps/dspserver-client.Tpo .deps/dspserver-client.Po
gcc -DHAVE_CONFIG_H -I. -I../../..    -O3 -Wall -I../../../trunk/src/DttSP -Wno-unused-function -L../../../trunk/src/DttSP -L.   -ffast-math -fopenmp  -march=native  -g -O2 -I/usr/include/libusb-1.0/ -I/usr/local/include/ -MT dspserver-audiostream.o -MD -MP -MF .deps/dspserver-audiostream.Tpo -c -o dspserver-audiostream.o `test -f 'audiostream.c' || echo './'`audiostream.c
mv -f .deps/dspserver-audiostream.Tpo .deps/dspserver-audiostream.Po
gcc -DHAVE_CONFIG_H -I. -I../../..    -O3 -Wall -I../../../trunk/src/DttSP -Wno-unused-function -L../../../trunk/src/DttSP -L.   -ffast-math -fopenmp  -march=native  -g -O2 -I/usr/include/libusb-1.0/ -I/usr/local/include/ -MT dspserver-register.o -MD -MP -MF .deps/dspserver-register.Tpo -c -o dspserver-register.o `test -f 'register.c' || echo './'`register.c
register.c: In function ‘doReg’:
register.c:66:14: warning: variable ‘result’ set but not used [-Wunused-but-set-variable]
   66 |     int len, result;
      |              ^~~~~~
register.c: In function ‘init_register’:
register.c:213:9: warning: variable ‘ret’ set but not used [-Wunused-but-set-variable]
  213 |     int ret;
      |         ^~~
register.c: In function ‘doUpdate’:
register.c:222:13: warning: variable ‘result’ set but not used [-Wunused-but-set-variable]
  222 |         int result;
      |             ^~~~~~
register.c: In function ‘updateStatus’:
register.c:243:9: warning: variable ‘ret’ set but not used [-Wunused-but-set-variable]
  243 |     int ret;
      |         ^~~
register.c: In function ‘doRemove’:
register.c:254:6: warning: variable ‘result’ set but not used [-Wunused-but-set-variable]
  254 |  int result;
      |      ^~~~~~
mv -f .deps/dspserver-register.Tpo .deps/dspserver-register.Po
gcc -DHAVE_CONFIG_H -I. -I../../..    -O3 -Wall -I../../../trunk/src/DttSP -Wno-unused-function -L../../../trunk/src/DttSP -L.   -ffast-math -fopenmp  -march=native  -g -O2 -I/usr/include/libusb-1.0/ -I/usr/local/include/ -MT dspserver-rtp.o -MD -MP -MF .deps/dspserver-rtp.Tpo -c -o dspserver-rtp.o `test -f 'rtp.c' || echo './'`rtp.c
mv -f .deps/dspserver-rtp.Tpo .deps/dspserver-rtp.Po
gcc -DHAVE_CONFIG_H -I. -I../../..    -O3 -Wall -I../../../trunk/src/DttSP -Wno-unused-function -L../../../trunk/src/DttSP -L.   -ffast-math -fopenmp  -march=native  -g -O2 -I/usr/include/libusb-1.0/ -I/usr/local/include/ -MT dspserver-G711A.o -MD -MP -MF .deps/dspserver-G711A.Tpo -c -o dspserver-G711A.o `test -f 'G711A.c' || echo './'`G711A.c
mv -f .deps/dspserver-G711A.Tpo .deps/dspserver-G711A.Po
/bin/bash ../../../libtool  --tag=CC   --mode=link gcc -O3 -Wall -I../../../trunk/src/DttSP -Wno-unused-function -L../../../trunk/src/DttSP -L.   -ffast-math -fopenmp  -march=native  -g -O2 -I/usr/include/libusb-1.0/ -I/usr/local/include/  -L/lib64 -L/usr/lib64 -o dspserver dspserver-main.o dspserver-ozy.o dspserver-soundcard.o dspserver-client.o dspserver-audiostream.o dspserver-register.o dspserver-rtp.o dspserver-G711A.o -lDttSP -lsdrutil -lrt -lssl -lcrypto  -lgomp -lortp -lsamplerate -levent_openssl -levent_pthreads -levent -lusb-1.0 -lconfig -ljack -lusb -lpulse -lpulse-simple -lcodec2 -lfftw3f -lportaudio -lpthread -lm 
libtool: link: gcc -O3 -Wall -I../../../trunk/src/DttSP -Wno-unused-function -ffast-math -fopenmp -march=native -g -O2 -I/usr/include/libusb-1.0/ -I/usr/local/include/ -o dspserver dspserver-main.o dspserver-ozy.o dspserver-soundcard.o dspserver-client.o dspserver-audiostream.o dspserver-register.o dspserver-rtp.o dspserver-G711A.o  -L../../../trunk/src/DttSP -L. -L/lib64 -L/usr/lib64 -lDttSP -lsdrutil -lrt -lssl -lcrypto -lgomp -lortp -lsamplerate -levent_openssl -levent_pthreads -levent -lusb-1.0 -lconfig -ljack -lusb -lpulse -lpulse-simple -lcodec2 -lfftw3f -lportaudio -lpthread -lm -fopenmp
/usr/bin/ld: cannot find -lsdrutil
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:469: dspserver] Error 1
make[2]: Leaving directory '/usr/local/src/ghpsdr3-alex/trunk/src/dspserver'
make[1]: *** [Makefile:432: all-recursive] Error 1
make[1]: Leaving directory '/usr/local/src/ghpsdr3-alex'
make: *** [Makefile:364: all] Error 2
`

**Comment by csylvain** [comment]
refer to the previous message from Roger E Critchlow Jr, February 19, 2019.

**Comment by thermochromic** [comment]
> refer to the previous message from Roger E Critchlow Jr, February 19, 2019.

That did the trick, thanks.

**Comment by coloboxp** [comment]
I'm having the same issue, I have not been able to fix it. 

Please could you clarify what's the trick on `Roger E Critchlow Jr, February 19, 2019.`'s post?

I read it over and over again, tried doing the make directly on the `libsdrtutil.a`, but I don't know (don't understand)  what has to be changed.
